import '../../domain/entities/tourist_place.dart';

const _templeScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'at-the-sights',
    labelEn: 'At the sights',
  ),
  RecommendedScene(
    categoryId: 'basics',
    subtopicId: 'asking',
    labelEn: 'Asking questions',
  ),
  RecommendedScene(
    categoryId: 'shopping',
    subtopicId: 'phrases',
    labelEn: 'Common shopping phrases',
  ),
];

const _towerScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'at-the-sights',
    labelEn: 'At the sights',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'tourist-info',
    labelEn: 'Tourist information center',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'photos',
    labelEn: 'Photos & video',
  ),
];

const _urbanScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'directions',
    labelEn: 'Asking for directions',
  ),
  RecommendedScene(
    categoryId: 'basics',
    subtopicId: 'confirming',
    labelEn: 'Confirming',
  ),
  RecommendedScene(
    categoryId: 'emergency',
    subtopicId: 'lost-stolen',
    labelEn: 'Loss & theft',
  ),
];

const _shrineScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'basics',
    subtopicId: 'asking',
    labelEn: 'Asking questions',
  ),
  RecommendedScene(
    categoryId: 'shopping',
    subtopicId: 'phrases',
    labelEn: 'Common shopping phrases',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'tourist-info',
    labelEn: 'Tourist information center',
  ),
];

const _parkScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'tourist-info',
    labelEn: 'Tourist information center',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'at-the-sights',
    labelEn: 'At the sights',
  ),
  RecommendedScene(
    categoryId: 'facilities',
    subtopicId: 'restroom',
    labelEn: 'Restroom',
  ),
];

const _heritageScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'at-the-sights',
    labelEn: 'At the sights',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'directions',
    labelEn: 'Asking for directions',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'photos',
    labelEn: 'Photos & video',
  ),
];

const _museumScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'at-the-sights',
    labelEn: 'At the sights',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'tourist-info',
    labelEn: 'Tourist information center',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'photos',
    labelEn: 'Photos & video',
  ),
];

const _marketScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'restaurant',
    subtopicId: 'menu',
    labelEn: 'Choosing from the menu',
  ),
  RecommendedScene(
    categoryId: 'shopping',
    subtopicId: 'phrases',
    labelEn: 'Common shopping phrases',
  ),
  RecommendedScene(
    categoryId: 'shopping',
    subtopicId: 'paying',
    labelEn: 'Paying',
  ),
];

const _shoppingScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'shopping',
    subtopicId: 'finding-shops',
    labelEn: 'Finding shops',
  ),
  RecommendedScene(
    categoryId: 'shopping',
    subtopicId: 'phrases',
    labelEn: 'Common shopping phrases',
  ),
  RecommendedScene(
    categoryId: 'shopping',
    subtopicId: 'paying',
    labelEn: 'Paying',
  ),
];

const _natureScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'directions',
    labelEn: 'Asking for directions',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'tourist-info',
    labelEn: 'Tourist information center',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'photos',
    labelEn: 'Photos & video',
  ),
];

const _waterfrontScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'directions',
    labelEn: 'Asking for directions',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'photos',
    labelEn: 'Photos & video',
  ),
  RecommendedScene(
    categoryId: 'restaurant',
    subtopicId: 'finding',
    labelEn: 'Finding a restaurant',
  ),
];

const _gardenScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'tourist-info',
    labelEn: 'Tourist information center',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'at-the-sights',
    labelEn: 'At the sights',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'photos',
    labelEn: 'Photos & video',
  ),
];

const _familyAttractionScenes = <RecommendedScene>[
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'at-the-sights',
    labelEn: 'At the sights',
  ),
  RecommendedScene(
    categoryId: 'sightseeing',
    subtopicId: 'tourist-info',
    labelEn: 'Tourist information center',
  ),
  RecommendedScene(
    categoryId: 'restaurant',
    subtopicId: 'dining',
    labelEn: 'During the meal',
  ),
];

const _recommendationsByPlaceId = <int, List<RecommendedScene>>{
  101: _heritageScenes,
  102: _heritageScenes,
  103: _towerScenes,
  104: _shoppingScenes,
  105: _museumScenes,
  201: _waterfrontScenes,
  202: _heritageScenes,
  203: _marketScenes,
  204: _templeScenes,
  205: _waterfrontScenes,
  301: _natureScenes,
  302: _natureScenes,
  303: _natureScenes,
  304: _natureScenes,
  305: _museumScenes,
  401: _templeScenes,
  402: _heritageScenes,
  403: _heritageScenes,
  404: _gardenScenes,
  405: _heritageScenes,
  501: _heritageScenes,
  502: _shrineScenes,
  503: _heritageScenes,
  504: _marketScenes,
  505: _natureScenes,
  1101: _templeScenes,
  1102: _shrineScenes,
  1103: _urbanScenes,
  1104: _towerScenes,
  1105: _parkScenes,
  1201: _heritageScenes,
  1202: _marketScenes,
  1203: _heritageScenes,
  1204: _shrineScenes,
  1205: _towerScenes,
  1301: _shrineScenes,
  1302: _templeScenes,
  1303: _templeScenes,
  1304: _natureScenes,
  1305: _heritageScenes,
  1401: _parkScenes,
  1402: _shrineScenes,
  1403: _towerScenes,
  1404: _shrineScenes,
  1405: _shoppingScenes,
  1501: _parkScenes,
  1502: _heritageScenes,
  1503: _natureScenes,
  1504: _shrineScenes,
  1505: _marketScenes,
  2101: _heritageScenes,
  2102: _templeScenes,
  2103: _gardenScenes,
  2104: _natureScenes,
  2105: _templeScenes,
  2201: _waterfrontScenes,
  2202: _gardenScenes,
  2203: _towerScenes,
  2204: _templeScenes,
  2205: _marketScenes,
  2301: _museumScenes,
  2302: _heritageScenes,
  2303: _templeScenes,
  2304: _marketScenes,
  2305: _museumScenes,
  2401: _familyAttractionScenes,
  2402: _shrineScenes,
  2403: _marketScenes,
  2404: _parkScenes,
  2405: _templeScenes,
  2501: _towerScenes,
  2502: _museumScenes,
  2503: _heritageScenes,
  2504: _parkScenes,
  2505: _heritageScenes,
};

TouristPlace _place(
  int id,
  int cityId,
  String nameEn,
  String nameLocal,
  String descriptionEn,
  double mapX,
  double mapY,
) => TouristPlace(
  id: id,
  cityId: cityId,
  nameEn: nameEn,
  nameLocal: nameLocal,
  descriptionEn: descriptionEn,
  mapX: mapX,
  mapY: mapY,
  recommendedScenes: _recommendationsByPlaceId[id]!,
);

final touristPlacesSeed = List<TouristPlace>.unmodifiable([
  // Seoul
  _place(
    101,
    1,
    'Gyeongbokgung Palace',
    '경복궁',
    'The grand main palace of the Joseon dynasty.',
    0.42,
    0.25,
  ),
  _place(
    102,
    1,
    'Bukchon Hanok Village',
    '북촌한옥마을',
    'A hillside neighborhood of traditional Korean homes.',
    0.56,
    0.28,
  ),
  _place(
    103,
    1,
    'N Seoul Tower',
    'N서울타워',
    'A landmark tower with panoramic city views.',
    0.48,
    0.55,
  ),
  _place(
    104,
    1,
    'Myeongdong',
    '명동',
    'A lively district known for shopping and street food.',
    0.51,
    0.47,
  ),
  _place(
    105,
    1,
    'Dongdaemun Design Plaza',
    '동대문디자인플라자',
    'A futuristic cultural complex and design hub.',
    0.68,
    0.49,
  ),

  // Busan
  _place(
    201,
    2,
    'Haeundae Beach',
    '해운대해수욕장',
    'Busan’s best-known beach and waterfront promenade.',
    0.72,
    0.31,
  ),
  _place(
    202,
    2,
    'Gamcheon Culture Village',
    '감천문화마을',
    'Colorful hillside lanes filled with art and viewpoints.',
    0.28,
    0.58,
  ),
  _place(
    203,
    2,
    'Jagalchi Market',
    '자갈치시장',
    'A bustling seafood market beside the harbor.',
    0.34,
    0.62,
  ),
  _place(
    204,
    2,
    'Haedong Yonggungsa Temple',
    '해동용궁사',
    'A rare seaside Buddhist temple on a rocky coast.',
    0.86,
    0.23,
  ),
  _place(
    205,
    2,
    'Gwangalli Beach',
    '광안리해수욕장',
    'A city beach with views of Gwangan Bridge.',
    0.61,
    0.42,
  ),

  // Jeju
  _place(
    301,
    3,
    'Seongsan Ilchulbong',
    '성산일출봉',
    'A volcanic tuff cone famous for sunrise views.',
    0.84,
    0.38,
  ),
  _place(
    302,
    3,
    'Hallasan National Park',
    '한라산국립공원',
    'Mountain trails through Jeju’s volcanic heart.',
    0.49,
    0.49,
  ),
  _place(
    303,
    3,
    'Manjanggul Cave',
    '만장굴',
    'One of the world’s longest accessible lava tubes.',
    0.73,
    0.27,
  ),
  _place(
    304,
    3,
    'Jeongbang Waterfall',
    '정방폭포',
    'A dramatic waterfall that drops toward the sea.',
    0.57,
    0.75,
  ),
  _place(
    305,
    3,
    'O’Sulloc Tea Museum',
    '오설록 티뮤지엄',
    'Tea fields and exhibits about Korean tea culture.',
    0.26,
    0.53,
  ),

  // Gyeongju
  _place(
    401,
    4,
    'Bulguksa Temple',
    '불국사',
    'A UNESCO-listed temple from the Silla kingdom.',
    0.73,
    0.58,
  ),
  _place(
    402,
    4,
    'Seokguram Grotto',
    '석굴암',
    'A mountain grotto housing a serene stone Buddha.',
    0.79,
    0.47,
  ),
  _place(
    403,
    4,
    'Daereungwon Tomb Complex',
    '대릉원',
    'Ancient royal tombs set in a peaceful park.',
    0.42,
    0.48,
  ),
  _place(
    404,
    4,
    'Donggung Palace and Wolji Pond',
    '동궁과 월지',
    'Illuminated palace ruins reflected in a historic pond.',
    0.55,
    0.46,
  ),
  _place(
    405,
    4,
    'Cheomseongdae Observatory',
    '첨성대',
    'A distinctive seventh-century astronomical observatory.',
    0.48,
    0.51,
  ),

  // Jeonju
  _place(
    501,
    5,
    'Jeonju Hanok Village',
    '전주한옥마을',
    'A large district of hanok homes and craft shops.',
    0.55,
    0.48,
  ),
  _place(
    502,
    5,
    'Gyeonggijeon Shrine',
    '경기전',
    'A historic shrine with royal portraits and quiet grounds.',
    0.49,
    0.47,
  ),
  _place(
    503,
    5,
    'Jeondong Cathedral',
    '전동성당',
    'A Romanesque church beside the hanok village.',
    0.46,
    0.51,
  ),
  _place(
    504,
    5,
    'Nambu Market',
    '남부시장',
    'A traditional market with a popular evening food scene.',
    0.43,
    0.56,
  ),
  _place(
    505,
    5,
    'Omokdae Pavilion',
    '오목대',
    'A hilltop pavilion overlooking tiled hanok roofs.',
    0.62,
    0.43,
  ),

  // Tokyo
  _place(
    1101,
    11,
    'Senso-ji Temple',
    '浅草寺',
    'Tokyo’s oldest temple and the heart of historic Asakusa.',
    0.73,
    0.27,
  ),
  _place(
    1102,
    11,
    'Meiji Shrine',
    '明治神宮',
    'A tranquil Shinto shrine surrounded by forest.',
    0.31,
    0.48,
  ),
  _place(
    1103,
    11,
    'Shibuya Crossing',
    '渋谷スクランブル交差点',
    'The iconic pedestrian crossing in central Shibuya.',
    0.33,
    0.61,
  ),
  _place(
    1104,
    11,
    'Tokyo Skytree',
    '東京スカイツリー',
    'A soaring broadcast tower with observation decks.',
    0.81,
    0.31,
  ),
  _place(
    1105,
    11,
    'Ueno Park',
    '上野公園',
    'A spacious park with museums, a zoo, and tree-lined walking paths.',
    0.52,
    0.38,
  ),

  // Osaka
  _place(
    1201,
    12,
    'Osaka Castle',
    '大阪城',
    'A reconstructed landmark surrounded by broad parkland.',
    0.57,
    0.35,
  ),
  _place(
    1202,
    12,
    'Dotonbori',
    '道頓堀',
    'A neon-lit canal district famous for local food.',
    0.45,
    0.54,
  ),
  _place(
    1203,
    12,
    'Shinsekai',
    '新世界',
    'A retro entertainment district beneath Tsutenkaku.',
    0.47,
    0.68,
  ),
  _place(
    1204,
    12,
    'Sumiyoshi Taisha',
    '住吉大社',
    'An ancient shrine with a graceful arched bridge.',
    0.39,
    0.82,
  ),
  _place(
    1205,
    12,
    'Umeda Sky Building',
    '梅田スカイビル',
    'Twin towers joined by a rooftop observatory.',
    0.43,
    0.24,
  ),

  // Kyoto
  _place(
    1301,
    13,
    'Fushimi Inari Taisha',
    '伏見稲荷大社',
    'A mountainside shrine lined with thousands of red gates.',
    0.59,
    0.72,
  ),
  _place(
    1302,
    13,
    'Kiyomizu-dera Temple',
    '清水寺',
    'A celebrated wooden temple overlooking eastern Kyoto.',
    0.68,
    0.48,
  ),
  _place(
    1303,
    13,
    'Kinkaku-ji',
    '金閣寺',
    'The Golden Pavilion reflected in a garden pond.',
    0.31,
    0.25,
  ),
  _place(
    1304,
    13,
    'Arashiyama Bamboo Grove',
    '嵐山竹林',
    'A pathway through towering bamboo in western Kyoto.',
    0.18,
    0.52,
  ),
  _place(
    1305,
    13,
    'Gion',
    '祇園',
    'A preserved district of teahouses and traditional lanes.',
    0.61,
    0.46,
  ),

  // Fukuoka
  _place(
    1401,
    14,
    'Ohori Park',
    '大濠公園',
    'A spacious city park centered on a large pond.',
    0.36,
    0.43,
  ),
  _place(
    1402,
    14,
    'Kushida Shrine',
    '櫛田神社',
    'A historic shrine associated with the Hakata Gion festival.',
    0.57,
    0.52,
  ),
  _place(
    1403,
    14,
    'Fukuoka Tower',
    '福岡タワー',
    'A seaside tower offering wide views over Hakata Bay.',
    0.24,
    0.34,
  ),
  _place(
    1404,
    14,
    'Dazaifu Tenmangu',
    '太宰府天満宮',
    'A major shrine dedicated to scholarship and learning.',
    0.78,
    0.78,
  ),
  _place(
    1405,
    14,
    'Canal City Hakata',
    'キャナルシティ博多',
    'A colorful shopping and entertainment complex.',
    0.55,
    0.58,
  ),

  // Sapporo
  _place(
    1501,
    15,
    'Odori Park',
    '大通公園',
    'A green avenue running through central Sapporo.',
    0.49,
    0.49,
  ),
  _place(
    1502,
    15,
    'Sapporo Clock Tower',
    '札幌市時計台',
    'A small wooden landmark from the city’s early years.',
    0.53,
    0.45,
  ),
  _place(
    1503,
    15,
    'Mount Moiwa',
    '藻岩山',
    'A forested mountain known for sweeping night views.',
    0.35,
    0.72,
  ),
  _place(
    1504,
    15,
    'Hokkaido Shrine',
    '北海道神宮',
    'A wooded Shinto shrine near Maruyama Park.',
    0.32,
    0.48,
  ),
  _place(
    1505,
    15,
    'Nijo Market',
    '二条市場',
    'A compact market specializing in Hokkaido seafood.',
    0.56,
    0.51,
  ),

  // Beijing
  _place(
    2101,
    21,
    'Forbidden City',
    '故宫',
    'The vast imperial palace at the center of Beijing.',
    0.49,
    0.43,
  ),
  _place(
    2102,
    21,
    'Temple of Heaven',
    '天坛',
    'An imperial ceremonial complex set in a large park.',
    0.52,
    0.64,
  ),
  _place(
    2103,
    21,
    'Summer Palace',
    '颐和园',
    'Lakeside imperial gardens northwest of the city.',
    0.28,
    0.25,
  ),
  _place(
    2104,
    21,
    'Mutianyu Great Wall',
    '慕田峪长城',
    'A scenic restored section of the Great Wall.',
    0.78,
    0.14,
  ),
  _place(
    2105,
    21,
    'Lama Temple',
    '雍和宫',
    'An ornate Tibetan Buddhist temple complex.',
    0.55,
    0.32,
  ),

  // Shanghai
  _place(
    2201,
    22,
    'The Bund',
    '外滩',
    'A waterfront promenade facing Pudong’s skyline.',
    0.55,
    0.48,
  ),
  _place(
    2202,
    22,
    'Yu Garden',
    '豫园',
    'A classical garden of pavilions, ponds, and rockeries.',
    0.58,
    0.55,
  ),
  _place(
    2203,
    22,
    'Shanghai Tower',
    '上海中心大厦',
    'China’s tallest skyscraper with a high observation deck.',
    0.63,
    0.48,
  ),
  _place(
    2204,
    22,
    'Jade Buddha Temple',
    '玉佛禅寺',
    'An active temple known for its carved jade Buddhas.',
    0.39,
    0.42,
  ),
  _place(
    2205,
    22,
    'Tianzifang',
    '田子坊',
    'A maze of arts, crafts, cafés, and historic lanes.',
    0.45,
    0.61,
  ),

  // Xi'an
  _place(
    2301,
    23,
    'Terracotta Army',
    '兵马俑',
    'Thousands of clay soldiers guarding an imperial tomb.',
    0.82,
    0.38,
  ),
  _place(
    2302,
    23,
    'Xi’an City Wall',
    '西安城墙',
    'A monumental and remarkably complete ancient city wall.',
    0.49,
    0.51,
  ),
  _place(
    2303,
    23,
    'Giant Wild Goose Pagoda',
    '大雁塔',
    'A Tang-era pagoda and important Buddhist landmark.',
    0.53,
    0.68,
  ),
  _place(
    2304,
    23,
    'Muslim Quarter',
    '回民街',
    'Bustling lanes filled with food stalls and local specialties.',
    0.46,
    0.43,
  ),
  _place(
    2305,
    23,
    'Shaanxi History Museum',
    '陕西历史博物馆',
    'A major collection spanning China’s ancient dynasties.',
    0.51,
    0.63,
  ),

  // Chengdu
  _place(
    2401,
    24,
    'Chengdu Research Base of Giant Panda Breeding',
    '成都大熊猫繁育研究基地',
    'A conservation center where visitors can see giant pandas.',
    0.67,
    0.24,
  ),
  _place(
    2402,
    24,
    'Wuhou Shrine',
    '武侯祠',
    'A historic shrine honoring heroes of the Three Kingdoms.',
    0.43,
    0.59,
  ),
  _place(
    2403,
    24,
    'Jinli Ancient Street',
    '锦里古街',
    'A lantern-lit pedestrian street beside Wuhou Shrine.',
    0.41,
    0.61,
  ),
  _place(
    2404,
    24,
    'People’s Park',
    '人民公园',
    'A relaxed central park known for its traditional teahouse.',
    0.47,
    0.48,
  ),
  _place(
    2405,
    24,
    'Wenshu Monastery',
    '文殊院',
    'A peaceful Buddhist monastery with gardens and teahouses.',
    0.51,
    0.39,
  ),

  // Guangzhou
  _place(
    2501,
    25,
    'Canton Tower',
    '广州塔',
    'A slender landmark tower overlooking the Pearl River.',
    0.58,
    0.59,
  ),
  _place(
    2502,
    25,
    'Chen Clan Ancestral Hall',
    '陈家祠',
    'An ornate complex showcasing traditional Cantonese craft.',
    0.38,
    0.44,
  ),
  _place(
    2503,
    25,
    'Shamian Island',
    '沙面岛',
    'A leafy river island lined with historic architecture.',
    0.32,
    0.56,
  ),
  _place(
    2504,
    25,
    'Yuexiu Park',
    '越秀公园',
    'A large urban park containing the Five Rams statue.',
    0.46,
    0.31,
  ),
  _place(
    2505,
    25,
    'Sacred Heart Cathedral',
    '石室圣心大教堂',
    'A striking Gothic cathedral built from granite.',
    0.43,
    0.53,
  ),
]);
